### ISSUE TITLE
Need to install Apache Conf extension?

### ISSUE THREAD

**Issue by jtanaka** [hrdtbs/vscode-apacheconf-snippets#1]
Hello, thank you so much for providing great extension.

Is my understanding correct about need to install [Apache Conf](https://github.com/mrmlnc/vscode-apache) extension?

Doesn't work without Apache Conf.

**Comment by hrdtbs** [comment]
Sorry for the late reply.
Thank you for teaching me. 
After checking, it was true to need to install Apache Conf extension.
So I will add that to README.md.
