### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by tkoelpin** [hrdtbs/vscode-apacheconf-snippets#2]
Hello,

I like your Snippets for apacheconf, but I really need your license. Or should this be private?
Is this an open-source and suitable for commercial use?

Here is an extraction of your `package.json`:

````json
"license": "SEE LICENSE IN LICENSE.md",
````

**Comment by hrdtbs** [comment]
Thank you for teaching me. I will add a LICENSE.md.
Sorry, I am not good at English.
