### ISSUE TITLE
Syntax coloring issue: escaped space in regex

### ISSUE THREAD

**Issue by mblais** [hrdtbs/vscode-apacheconf-snippets#3]
Thanks for this great extension!
It does seem to get confused by an escaped space:

`RewriteCond %{REQUEST_URI} !^/\.well-known/pki-validation/[A-F0-9]{32}\.txt(?:\ Comodo\ DCV)?$`
![image](https://user-images.githubusercontent.com/281745/54011991-578f8980-4129-11e9-9235-751ace68d674.png)

**Comment by hrdtbs** [comment]
Sorry for my late reply.

Issues about syntax color-highlighting are due to [mrmlnc.vscode-apache](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-apache
) dependent on my extension.

My extension only supports syntax snippets.

I'm sorry I can not help.
