### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by SantoshPattnaik** [hrdtbs/vscode-apacheconf-snippets#5]
The extension is not working for me I don't know why. When I start typing 'a-' no snippets related to apache conf show only other snippets are shown.

**Comment by Amarok24** [comment]
Same here, does not work at all. Restart doesn't help.

Windows 10, VSCode 1.77.3

Extension page in VSCode, tab "RUNTIME STATUS" says:
Unknown language in `contributes.apacheconf-snippets.language`. Provided value: apacheconf

**Comment by viking1304** [comment]
I guess you need to install https://github.com/mrmlnc/vscode-apache first.

This extension works fine for me.

Just be aware that it has an outdated 2.2 syntax as primary, while the 2.4 syntax is commented out. It should be the other way around now.

**Comment by hrdtbs** [comment]
Thanks. I would add mrmlnc/vscode-apache to the `extensionDependencies`.
