### ISSUE TITLE
Apache 2.4 specific code

### ISSUE THREAD

**Issue by viking1304** [hrdtbs/vscode-apacheconf-snippets#6]
May you please update those snippets so 2.4 specific code is the default instead of outdated 2.2? An option to specify the Apache version in the config would be ideal.

I could easily fork this repo and do that myself, but I always prefer that the original author update his own code if possible.

**Comment by hrdtbs** [comment]
Thanks. I will change v2.2 to comment out for now.

> An option to specify the Apache version in the config would be ideal.

I too think this would be best.. But I don't know a good way to do it specifically.
